package br.com.agendeme.gestao.model.enums;

public enum Especialidade {
    CARDIOLOGISTA,
    CIRURGIAO_GERAL,
    CLINICO_GERAL,
    DERMATOLOGISTA,
    ENDOCRINOLOGISTA,
    GASTROENTEROLOGISTA,
    GERIATRA,
    GINECOLOGISTA,
    HEMATOLOGISTA,
    INFECTOLOGISTA,
    NEFROLOGISTA,
    NEUROLOGISTA,
    OFTALMOLOGISTA,
    ONCOLOGISTA,
    ORTOPEDISTA,
    OTORRINOLARINGOLOGISTA,
    PEDIATRA,
    PNEUMOLOGISTA,
    PSIQUIATRA,
    REUMATOLOGISTA,
    UROLOGISTA
}

