package br.com.agendeme.gestao.model.enums;

public enum Especialidade {
    CARDIOLOGIA,
    CIRURGIA_GERAL,
    CLINICA_GERAL,
    DERMATOLOGIA,
    ENDOCRINOLOGIA,
    GASTROENTEROLOGIA,
    GERIATRIA,
    GINECOLOGIA,
    HEMATOLOGIA,
    INFECTOLOGIA,
    NEFROLOGIA,
    NEUROLOGIA,
    OFTALMOLOGIA,
    ONCOLOGIA,
    ORTOPEDIA,
    OTORRINOLARINGOLOGIA,
    PEDIATRIA,
    PNEUMOLOGIA,
    PSIQUIATRIA,
    REUMATOLOGIA,
    UROLOGIA
}
